// Search
export const UPDATE_SEARCH_FORM = 'UPDATE_SEARCH_FORM';
export const FETCH_REPOS_INIT = 'FETCH_REPOS_INIT';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAIL = 'FETCH_REPOS_FAIL';

// Filters
export const UPDATE_FILTERS_FORM = 'UPDATE_FILTERS_FORM';
